# ====================================
# Google App Engine Configuration
# Moni-Personal GCP Edition
# ====================================

runtime: python311
instance_class: F2

# Configurações de auto-scaling
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

# Variáveis de ambiente para produção
env_variables:
  ENVIRONMENT: "production"
  FORCE_HTTPS: "true"
  PYTHONUNBUFFERED: "1"
  # Database - usar Cloud SQL Proxy ou configurar via Secret Manager
  # DATABASE_URL: "configurar via Secret Manager"

# Handlers para arquivos estáticos (otimização)
handlers:
  # Servir arquivos estáticos diretamente
  - url: /static
    static_dir: static
    secure: always
    redirect_http_response_code: 301
    expiration: "1d"
    http_headers:
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "DENY"
      X-XSS-Protection: "1; mode=block"

  # Redirecionar tudo para a aplicação
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

# Health check
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

# Rede VPC (opcional - para Cloud SQL)
# vpc_access_connector:
#   name: projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME

# Configurações de segurança
entrypoint: gunicorn -k uvicorn.workers.UvicornWorker -w 4 -b :$PORT --timeout 120 --access-logfile - --error-logfile - main:app
