apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monipersonal

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: monipersonal
  app.kubernetes.io/managed-by: kustomize
